### ISSUE TITLE
unsupport Ruby 2.6.0 or newer

### ISSUE THREAD

**Issue by fanxy1** [ryanfb/ruby-opencv#4]
I want to use opencv to do something, but my ruby version is 2.6.0, how to use opencv with 2.6 or newer

**Comment by bill1997603** [comment]
@ryanfb

**Comment by ryanfb** [comment]
Sorry, but this repo/gem is long-dead. Take a look at the more updated `ruby-opencv` instead: https://github.com/ruby-opencv/ruby-opencv/
